[project]
name = "rootdata-mcp-server"
version = "0.1.0"
description = "MCP server for RootData API integration"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
    "python-dotenv>=1.0.1",
]
